import { pgTable, text, timestamp, boolean, integer, real, uuid, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(), // Using text for CUIDs or UUIDs generated by client
  displayName: text('display_name').notNull(),
  avatarUrl: text('avatar_url'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const derbies = pgTable('derbies', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  bodyOfWaterName: text('body_of_water_name').notNull(),
  scoringMode: text('scoring_mode').notNull(), // 'length' | 'weight' | 'count'
  scoringUnit: text('scoring_unit'), // 'in' | 'cm' | 'lb' | 'kg'
  createdByUserId: text('created_by_user_id').notNull().references(() => users.id),
  startsAt: timestamp('starts_at'),
  endsAt: timestamp('ends_at'),
  isArchived: boolean('is_archived').default(false).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const derbyParticipants = pgTable('derby_participants', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  userId: text('user_id').notNull().references(() => users.id),
  nickname: text('nickname'),
  isAdmin: boolean('is_admin').default(false).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const catches = pgTable('catches', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  userId: text('user_id').notNull().references(() => users.id),
  species: text('species'),
  lengthInInches: real('length_in_inches'),
  weightInPounds: real('weight_in_pounds'),
  count: integer('count').notNull().default(1),
  photoUrl: text('photo_url'),
  caughtAt: timestamp('caught_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

export const chatMessages = pgTable('chat_messages', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  userId: text('user_id').notNull().references(() => users.id),
  text: text('text').notNull(),
  sentAt: timestamp('sent_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
