import { pgTable, text, timestamp, boolean, integer, real, serial, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(), // Using text for CUIDs or UUIDs generated by client
  displayName: text('display_name').notNull(),
  avatarUrl: text('avatar_url'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const derbies = pgTable('derbies', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  bodyOfWaterName: text('body_of_water_name').notNull(),
  scoringMode: text('scoring_mode').notNull(), // 'length' | 'weight' | 'count'
  scoringUnit: text('scoring_unit'), // 'in' | 'cm' | 'lb' | 'kg'
  scoringStyle: text('scoring_style'), // 'biggest' | 'best_n' | 'total'
  bestN: integer('best_n'),
  speciesFilter: text('species_filter'),
  inviteCode: text('invite_code'),
  status: text('status').default('draft'),
  createdByUserId: text('created_by_user_id').notNull().references(() => users.id),
  startsAt: timestamp('starts_at'),
  endsAt: timestamp('ends_at'),
  isArchived: boolean('is_archived').default(false).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const derbyParticipants = pgTable('derby_participants', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  userId: text('user_id').notNull().references(() => users.id),
  nickname: text('nickname'),
  isAdmin: boolean('is_admin').default(false).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const catches = pgTable('catches', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  userId: text('user_id').notNull().references(() => users.id),
  species: text('species'),
  lengthInInches: real('length_in_inches'),
  weightInPounds: real('weight_in_pounds'),
  count: integer('count').notNull().default(1),
  photoUrl: text('photo_url'),
  photoMediaId: text('photo_media_id'),
  note: text('note'),
  caughtAt: timestamp('caught_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
  clientId: text('client_id').notNull(), // Device that created this catch
});

export const chatMessages = pgTable('chat_messages', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  userId: text('user_id').notNull().references(() => users.id),
  text: text('text').notNull(),
  sentAt: timestamp('sent_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  clientId: text('client_id').notNull(), // Device that created this message
});

export const devices = pgTable('devices', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id), // Optional link to authenticated user
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const reactions = pgTable('reactions', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  userId: text('user_id').notNull().references(() => users.id),
  targetType: text('target_type').notNull(),
  targetId: text('target_id').notNull(),
  reaction: text('reaction').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  clientId: text('client_id').notNull(),
});

export const media = pgTable('media', {
  id: text('id').primaryKey(),
  ownerId: text('owner_id').notNull().references(() => users.id),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  catchId: text('catch_id'),
  contentHash: text('content_hash').notNull(),
  contentType: text('content_type').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  width: integer('width'),
  height: integer('height'),
  remoteUrl: text('remote_url'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  clientId: text('client_id').notNull(),
});

export const processedOperations = pgTable('processed_operations', {
  opId: text('op_id').primaryKey(),
  deviceId: text('device_id').notNull(),
  derbyId: text('derby_id'),
  result: jsonb('result').notNull(),
  processedAt: timestamp('processed_at').defaultNow().notNull(),
});

export const derbyEvents = pgTable('derby_events', {
  id: text('id').primaryKey(),
  derbyId: text('derby_id').notNull().references(() => derbies.id),
  sequence: serial('sequence').notNull(),
  entityType: text('entity_type'),
  entityId: text('entity_id'),
  type: text('type').notNull(),
  payload: jsonb('payload').notNull(),
  serverCreatedAt: timestamp('server_created_at').defaultNow().notNull(),
});
